project:
  type: website

website:
  title: "Jaime Arboleda"
  description: "A blog about data science, machine learning, statistics, programming, Python, R and much more..."
  site-url: https://jaime-arboleda.netlify.app/
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: index.qmd
      - icon: github
        href: https://github.com/JaimeArboleda
      - icon: linkedin
        href: https://www.linkedin.com/in/jaime-arboleda-castilla-1a676b207
      - icon: rss
        href: index.xml
        
date-format: "DD/MM/YYYY"

freeze: true

format:
  html:
    smooth-scroll: true
    code-copy: true
    theme: tango
    css: styles.css
    toc: true
    html-math-method: katex

comments:
  giscus:
    repo: JaimeArboleda/blog
